name: adventure_planner
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  animated_bottom_navigation_bar: ^1.3.3
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_gen: ^5.7.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.14
  fluttertoast: ^8.2.8
  freezed_annotation: ^2.4.4
  go_router: ^14.2.7
  google_fonts: ^6.2.1
  http: ^1.2.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  logger: ^2.4.0
  mesh_gradient: ^1.3.7
  shared_preferences: ^2.3.2
  smooth_sheets: ^0.10.0
  theme_tailor: ^3.0.1
  toastification: ^2.3.0
  url_launcher: ^6.3.0

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.12
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/bold/svg/
    - assets/icons/linear/svg/

flutter_gen:
  output: lib/resources/generated
  line_length: 160
  null_safety: true
  package_parameter_enabled: true
  integrations:
    flutter_svg: true
    lottie: true
  assets:
    enabled: true
#    exclude:

#      - assets/images/animations/

# Run the following command to generate the files:

#  fluttergen -h
#  fluttergen -c pubspec.yaml